// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PrepareForGitHub
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPrepForGitPackageString = "534b4a6d-f0bd-42bc-af1f-b00ebee1c783";
        public const string guidPrepForGitPackageCmdSetString = "8401d26a-522c-4302-8e2e-28fd6315ebed";
        public const string guidImagesString = "1dcf2249-d06f-44f8-8fba-4bc3574d04d9";
        public static Guid guidPrepForGitPackage = new Guid(guidPrepForGitPackageString);
        public static Guid guidPrepForGitPackageCmdSet = new Guid(guidPrepForGitPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int PrepForGitId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
