// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PrepareForGitHub
{
    static class Vsix
    {
        public const string Id = "7a42d726-bce1-4c17-8341-e455584ddb90";
        public const string Name = "Prepare For GitHub";
        public const string Description = @"Prepare your projects to upload to GitHub";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Vivian Lobo";
        public const string Tags = "github, gitignore, git";
    }
}
